### ISSUE TITLE
shutdown 机制

### ISSUE THREAD

**Issue by lamter** [shidenggui/easyquant#21]
- 我认为需要个 shutdown 机制，在进程终止前进行逻辑，如将 log 句柄 flush 到硬盘。
- 机制需要捕获以下进程终止信号：
1. signal.SIGQUIT,     # quit 信号
2. signal.SIGINT,      # 键盘信号
3. signal.SIGHUP,      # nohup 命令
4. signal.SIGTERM,     # kill 命令

**Comment by shidenggui** [comment]
已经实现

**Comment by tangbh** [comment]
现在不行了吗？
