### ISSUE TITLE
log的模式建议增加第三种设置的选项

### ISSUE THREAD

**Issue by EGQM** [shidenggui/easyquant#24]
第三种设置的选项为同时在屏幕输出和记录到文件中

**Comment by EGQM** [comment]
另外，在设置成屏幕输出日志的情况下，一旦把
self.user = easytrader.use(broker)
改成
self.user = easytrader.use(broker,debug=False)
很多信息将不再输出，比如引擎的启动等信息。

**Comment by shidenggui** [comment]
`easytrader` 采用的全局 `log` 等级的设置有点不合理，主要是使用的 `logbook` 库不太好用，有空我把它改成原生的 `logging` 库
