### ISSUE TITLE
clock_engine中moment事件无法触发

### ISSUE THREAD

**Issue by hahahay** [shidenggui/easyquant#43]
Jun 15, 2016 commit的clock_engine中moment事件无法触发，May 22, 2016的clock_engine版本正常。
目前看来Jun 15, 2016的clock_engine存在下面问题：

if self.is_trading_date and not etime.is_trade_date(self.clock_engine.now_dt):中，etime.is_trade_date前多了个not，导致交易日is_active变为False。应该去掉这个not。

**Comment by shidenggui** [comment]
我的理解是 15 号的版本无法触发 `clock moment` 是因为少了 `not` 。`is_trading_date` 是指 `clock` 引擎是否只在交易日触发(这个命名可能不太准确)。若为 `True`， 再判断 今天是不是休息日 `not etime.is_trade_date()`，若是休息日则返回 `False` 不触发`clock`

**Comment by shidenggui** [comment]
不过貌似 clock engine 现在确实有点问题，我有空花时间细读下代码
