### ISSUE TITLE
account.session存储出错

### ISSUE THREAD

**Issue by jifen001** [shidenggui/easyquant#45]
with open(ACCOUNT_OBJECT_FILE, 'wb') as f:
                    dill.dump(self.user, f)
佣金宝和雪球账号执行到上一行时出现错误：
TypeError: Cannot serialize socket object

**Comment by luwm001** [comment]
我也是这样的，雪球账号，运行到这步就停下来了。

**Comment by shidenggui** [comment]
直接删除这行，这里有兼容性问题

**Comment by shidenggui** [comment]
fix by commit  #b56d8450bde4c471e36572f1d655bc2c2dc9a49f
