### ISSUE TITLE
main_engine.py的66行编译不过。

### ISSUE THREAD

**Issue by matrixleon18** [shidenggui/easyquant#51]
self.quotation_engines.append(quotation_engine(self.event_engine, self.clock_engine))

这里的quotation_engine是一个str的类型。运行到这里直接错误退出。
错误类型：
                 TypeError: 'str' object is not callable
# 

原以为这里的 quotation_engine(....)应该是在quotation_engine.py里面定义的quotation_engine类。

但是没有找到。就在quotation_engine.py里面重新继承了一个quotation_engine才通过。

不知道哪里出了问题。

**Comment by shidenggui** [comment]
需要更详细的信息。 你 engine 传入的是 str ？ 需要一个可用engine的列表

**Comment by matrixleon18** [comment]
你对的。为了调试方便我重写了test.py 所以传进去是个str。现在改过来就好了。恩。

发给你看看。方便可以merge进去
