### ISSUE TITLE
登录账号报错

### ISSUE THREAD

**Issue by sontiq** [shidenggui/easyquant#57]
环境：win7

import easytrader
user = easytrader.use('yh_client')
user.prepare(user='123456',password='678900')

报错：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'prepare'

**Comment by shidenggui** [comment]
用login，不要用prepare

**Comment by sontiq** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'login'

**Comment by sanjumsheng** [comment]
@sontiq 兄弟，请问你的银河的加密密码是怎么拿到的，我网页登陆只拿得到cookie 啊，没有密码之类的
